### ISSUE TITLE
create spring boot project

### ISSUE THREAD

**Issue by sebinfrancis** [SelvaSabapathy/invoicifysms#1]
AC: update the same in github project

All dependencies are included: 
- [x] developer tools, 
- [x] jpa, 
- [x] spring web, 
- [x] lombock, 
- [x] h2, 
- [x] postgres, 
- [x] restdocs

requires  #5

**Comment by selvasabapathy** [comment]
Commit: https://github.com/SelvaSabapathy/invoicifysms/commit/741e2f109272b2d28c0832030402fecf4f2be84e

**Comment by sebinfrancis** [comment]
Pulled the code and build and test passed successfully

**Comment by selvasabapathy** [comment]
Closing manually as all work is complete.
